# Generated by Django 4.2.25 on 2025-12-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0008_alter_evento_frequencia_liberada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(db_index=True, help_text='* Campo obrigatório', max_length=350, verbose_name='Nome do evento *'),
        ),
    ]
